name: Security Scan

on:
  workflow_call:
    inputs:
      image-tag:
        required: true
        type: string

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Load Docker image
        run: docker load < image.tar

      - name: Install Trivy
        run: |
          sudo apt-get install wget apt-transport-https gnupg -y
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy -y

      - name: Run Trivy scan
        run: |
          trivy image --severity CRITICAL --ignore-unfixed devops-project:${{ inputs.image-tag }}
          echo "Exit code: $?"

      - name: Fail if critical found
        run: |
          trivy image --severity CRITICAL --ignore-unfixed --exit-code 1 devops-project:${{ inputs.image-tag }}
